services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    restart: unless-stopped
    ports:
      - "4566:4566"
    environment:
      - SQS_PROVIDER=elasticmq
      - SERVICES=sqs,lambda,cloudformation,logs,iam,cloudwatch
      - DEBUG=0
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 3s
      retries: 10
  chat-app:
    image: chat-app:latest
    container_name: chat-app
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      mysql:
        condition: service_healthy
      localstack:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      sqs_endpoint: http://localstack:4566
